// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByz5Y5K1ITFxgWNMRoXai9cm0ZeXWDGcI',
    appId: '1:547881474372:web:483e8509a41d63c8629f11',
    messagingSenderId: '547881474372',
    projectId: 'scaventory',
    authDomain: 'scaventory.firebaseapp.com',
    storageBucket: 'scaventory.firebasestorage.app',
    measurementId: 'G-CZ50NRL8FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBVRi6QSMAFysiv1UK-HSlrQYhNqMIv2k',
    appId: '1:547881474372:android:da40878ebde7ad21629f11',
    messagingSenderId: '547881474372',
    projectId: 'scaventory',
    storageBucket: 'scaventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4L-YIo4BXeY3V7piEloRDzpbCysUtv6E',
    appId: '1:547881474372:ios:8946a93cc9c39ffe629f11',
    messagingSenderId: '547881474372',
    projectId: 'scaventory',
    storageBucket: 'scaventory.firebasestorage.app',
    iosBundleId: 'com.example.group2scanventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4L-YIo4BXeY3V7piEloRDzpbCysUtv6E',
    appId: '1:547881474372:ios:8946a93cc9c39ffe629f11',
    messagingSenderId: '547881474372',
    projectId: 'scaventory',
    storageBucket: 'scaventory.firebasestorage.app',
    iosBundleId: 'com.example.group2scanventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByz5Y5K1ITFxgWNMRoXai9cm0ZeXWDGcI',
    appId: '1:547881474372:web:266448419b250e73629f11',
    messagingSenderId: '547881474372',
    projectId: 'scaventory',
    authDomain: 'scaventory.firebaseapp.com',
    storageBucket: 'scaventory.firebasestorage.app',
    measurementId: 'G-2CNLD479H6',
  );
}
